import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Building2, Network, GraduationCap, Church, AudioLines, Monitor, Landmark } from 'lucide-react';
import { industries, process, credentials } from '@/data/site';
import { contentRepository } from '@/services/content';
import type { Project } from '@/types/domain';
import { Button, SectionHeading, ServiceIcon } from './ui';
export function CertificationStrip() { return <div className="trust-strip container"><span>CONNECTED EXPERTISE</span><div>COMMERCIAL AV</div><div>SYSTEM COMMISSIONING</div><div>LIVE PRODUCTION</div><div>EQUIPMENT RENTAL</div></div>; }
export function ServicesSection() { return <section className="section container"><SectionHeading eyebrow="01 / What we do" title="Technical depth. Practical delivery." text="Specialist support at every stage of your AV project." action={{ href: '/services', label: 'All services' }}/><div className="service-grid">{contentRepository.services().map((s, i) => <Link className="service-card" key={s.slug} href={`/services/${s.slug}`}><div className="card-top"><ServiceIcon index={i}/><span>0{i + 1}</span></div><h3>{s.title}</h3><p>{s.short}</p><ArrowUpRight className="card-arrow" size={19}/></Link>)}</div></section>; }
export function IndustriesSection({ all = false }: {
    all?: boolean;
}) { const icons = [Building2, Network, GraduationCap, Church, AudioLines, Monitor, Landmark]; return <section className="section industry-section"><div className="container"><SectionHeading eyebrow="02 / Where we work" title="Different spaces. One technical standard." text="AV support built around the way your space is used." action={all ? undefined : { href: '/industries', label: 'Explore industries' }}/><div className="industry-grid">{industries.slice(0, all ? 7 : 4).map((item, i) => { const Icon = icons[i]; return <article className="industry-card" key={item.name}><div className="industry-visual"><Icon size={70} strokeWidth={1}/><span>ENV / 0{i + 1}</span></div><h3>{item.name}</h3><p>{item.description}</p><Link className="text-link" href={`/quote?service=Other&context=${encodeURIComponent(item.name)}`}>Discuss your space<ArrowUpRight size={16}/></Link></article>; })}</div></div></section>; }
export function ProcessTimeline() { return <section className="section container"><SectionHeading eyebrow="03 / How we work" title="A clear path to a working system."/><ol className="process-grid">{process.map((p, i) => <li key={p.title}><span className="step-number">0{i + 1}</span><h3>{p.title}</h3><p>{p.text}</p></li>)}</ol></section>; }
export function ProjectCard({ project: p }: {
    project: Project;
}) { return <Link className="project-card" href={`/projects/${p.slug}`}><div className="project-image"><Image src={p.image} alt={`Illustrative AV equipment for ${p.title}`} fill sizes="(max-width: 700px) 100vw, 33vw"/><span className="sample-label">Sample project</span><span className="project-open"><ArrowUpRight /></span></div><span className="eyebrow">{p.industry} / {p.service.split(' / ')[0]}</span><h3>{p.title}</h3><p>{p.summary}</p></Link>; }
export function ProjectsSection() { return <section className="section project-section"><div className="container"><SectionHeading eyebrow="04 / Project perspectives" title="The work behind the experience." text="Illustrative project profiles. Real project case studies are coming soon." action={{ href: '/projects', label: 'View projects' }}/><div className="project-grid">{contentRepository.projects().map(p => <ProjectCard key={p.slug} project={p}/>)}</div></div></section>; }
export function ExperienceSection() { const approved = credentials.filter(c => c.verified); return <section className="section container expertise"><div><span className="eyebrow">05 / Technical foundations</span><h2>Details matter.<br />Especially the ones<br />you don’t see.</h2></div><div><p className="lead">Signal flow. Network configuration. Control logic. The fundamentals that make an AV system feel effortless.</p><div className="expertise-lines">{['Audio, video & control', 'AV networking & system verification', 'DSP & integrated workflows', 'Live production & field support'].map((x, i) => <div key={x}><span>0{i + 1}</span>{x}</div>)}</div>{approved.length > 0 && <div>{approved.map(c => <span key={c.name}>{c.name}</span>)}</div>}</div></section>; }
export function RentalTeaser() { return <section className="rental-teaser"><div className="container rental-inner"><div><span className="eyebrow">06 / Equipment rental</span><h2>The right gear.<br />Backed by technical<br />understanding.</h2><p>Audio, projection, video and the connections in between. Build a rental request and let’s work out the details.</p><Button href="/rental">Browse rental equipment</Button></div><div className="rental-category-list">{['Audio & microphones', 'Mixers & speakers', 'Projection & lenses', 'Video, lighting & accessories'].map((x, i) => <Link href="/rental" key={x}><span>0{i + 1}</span>{x}<ArrowUpRight /></Link>)}</div></div></section>; }
