'use client';
import { useState } from 'react';
import { useRentalBasket } from '@/lib/use-rental-basket';
import { equipmentCategories } from '@/data/catalog';
import type { Equipment } from '@/types/domain';
import { EquipmentCard } from './equipment-card';
import { InquiryForm } from './inquiry-form';
export function RentalCatalog({ equipment }: {
    equipment: Equipment[];
}) { const [category, setCategory] = useState('All equipment'); const [lines, setLines] = useRentalBasket(equipment); const [announcement, setAnnouncement] = useState(''); function add(e: Equipment) { setLines(old => { const existing = old.find(x => x.equipmentId === e.id); return existing ? old.map(x => x.equipmentId === e.id ? { ...x, quantity: Math.min(e.quantity, x.quantity + 1) } : x) : [...old, { equipmentId: e.id, quantity: 1 }]; }); setAnnouncement(`${e.model} added to your rental request.`); } return <><div className="notice">Sample catalog: these entries demonstrate rental requests. Models, stock, pricing and availability require owner confirmation. No reservation or payment is made.</div><div className="section-heading"><p>Select equipment, then tell us when you need it.</p><a className="text-link" href="#rental-request">Your request ({lines.reduce((n, x) => n + x.quantity, 0)}) ↓</a></div><div className="filter-bar" aria-label="Equipment categories">{['All equipment', ...equipmentCategories].map(c => <button key={c} aria-pressed={category === c} onClick={() => setCategory(c)}>{c}</button>)}</div><p role="status" aria-live="polite" className="form-note">{announcement}</p><div className="catalog-layout"><div className="equipment-grid">{equipment.filter(e => category === 'All equipment' || e.category === category).map(e => <EquipmentCard key={e.id} equipment={e} onAdd={() => add(e)} disabled={(lines.find(x => x.equipmentId === e.id)?.quantity || 0) >= e.quantity}/>)}</div><aside className="rental-request" id="rental-request"><span className="eyebrow">Your equipment list</span><h2>Rental request</h2>{!lines.length ? <p className="empty">Your request is empty. Add equipment from the catalog to get started.</p> : lines.map(line => { const e = equipment.find(x => x.id === line.equipmentId)!; return <div className="rental-line" key={line.equipmentId}><strong>{e.model}</strong><div className="rental-line-controls"><label htmlFor={`qty-${e.id}`}>Qty</label><input id={`qty-${e.id}`} type="number" min={1} max={e.quantity} value={line.quantity} onChange={event => { const n = Math.max(1, Math.min(e.quantity, Math.trunc(Number(event.target.value) || 1))); setLines(old => old.map(x => x.equipmentId === e.id ? { ...x, quantity: n } : x)); }}/><button className="remove-button" aria-label={`Remove ${e.model}`} onClick={() => setLines(old => old.filter(x => x.equipmentId !== e.id))}>Remove</button></div></div>; })}<InquiryForm kind="rental" items={lines} onSuccess={() => setLines([])}/></aside></div></>; }
